name: CI

on:
  push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: rustup toolchain install
        uses: dtolnay/rust-toolchain@v1

      - name: Test all Rust projects
        run: |
          find . -name Cargo.toml -execdir cargo test --verbose \;  

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: rustup toolchain install
        uses: dtolnay/rust-toolchain@v1

      - name: Build all Rust projects
        run: |
          find . -name Cargo.toml -execdir cargo build --verbose \;