name: CI

on:
  push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build all Rust projects
        run: |
          find . -name Cargo.toml -execdir cargo build --verbose \;

      - name: Test all Rust projects
        run: |
          find . -name Cargo.toml -execdir cargo test --verbose \;